[package]
edition = "2021"
license = "MIT"
name = "delanocreds"
version = "0.2.0"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
bls12_381_plus = "0.8.5"
anyhow = "1.0.70"
cid = "0.10.1"
multihash = "0.18.1"
secrecy = "0.8.0"
sha2 = { version = "0.10" }
rand = "0.8.5"
rayon = "1.8.0"
log = "0.4"
env_logger = "0.10.0"
delano-keys = { workspace = true }

# optional dependencies
serde = { version = "1.0", optional = true, features = ["derive"] }
# wa-serde-derive = "0.1"                                     # serde-derive in webassembly                                     # serde-derive for wasm

