[workspace]
members = [".", "crates/delano-crypto", "crates/delanocreds"]
resolver = "2"

[workspace.dependencies]
delano-crypto = { path = "crates/delano-crypto" }
delanocreds = { path = "crates/delanocreds" }

[package]
edition = "2021"
name = "delanocreds-bin"
version = "0.1.0"
# path = "src/bin/main.rs"

[dependencies]
anyhow = "1.0.44"
delano-crypto = { workspace = true }
delanocreds = { workspace = true }

[dev-dependencies]
delano-crypto = { workspace = true }

[profile.release]
codegen-units = 1        # allow for maximum size reduction optimizations
debug = false
debug-assertions = false
incremental = false
lto = true               # Enable Link Time Optimization
opt-level = 3            # Optimize for size
overflow-checks = false
panic = 'abort'          # Abort on panic
rpath = false
strip = true             # Automatically strip symbols from the binary.
