[workspace]
members = [".", "crates/*"]
resolver = "2"

[workspace.dependencies]
delanocreds = { path = "crates/delanocreds" }
delano-keys = { path = "crates/delano-keys" }
blastkids = "0.1"
bls12_381_plus = "0.8.5"
secrecy = "0.8"

[package]
edition = "2021"
license = "MIT"
name = "delanocreds-bin"
version = "0.1.0"

[dependencies]
anyhow = "1.0.44"
delanocreds = { workspace = true }
blastkids = { workspace = true }

[dev-dependencies]
blastkids = { workspace = true }
delano-keys = { workspace = true }
secrecy = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[profile.release]
codegen-units = 1        # allow for maximum size reduction optimizations
debug = false
debug-assertions = false
incremental = false
lto = true               # Enable Link Time Optimization
opt-level = 3            # Optimize for size
overflow-checks = false
panic = 'abort'          # Abort on panic
rpath = false
strip = true             # Automatically strip symbols from the binary.

[patch.crates-io]
bls12_381_plus = { git = "https://github.com/DougAnderson444/bls12_381_plus", branch = "wasm" }
