[package]
name = "delanocreds"
version = "0.1.1"
edition = "2021"

[dependencies]
amcl_wrapper = { version = "0.4.0", features = ["bls381"] }
sha2 = { version = "0.10" }
anyhow = "1.0.70"
secrecy = "0.8.0"
# serde = "1.0"
# wa-serde-derive = "0.1"                                     # serde-derive in webassembly                                     # serde-derive for wasm

# applies to build scripts and proc-macros (serde) to optimize compile times
# [profile.dev.build-override]
# opt-level = 3
