[workspace]
members = ["crates/delano-secrets", "crates/delanocreds"]
resolver = "2"

[workspace.dependencies]
delano-secrets = { path = "crates/delano-secrets" }
delanocreds = { path = "crates/delanocreds" }
