[package]
name = "delano-keys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blastkids = { workspace = true }
bls12_381_plus = { workspace = true }
secrecy = "0.8.0"
