[package]
name = "delano-keys"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
blastkids = { workspace = true } 
bls12_381_plus = { workspace = true, features = ["alloc"] }
bincode = "1.3.3"
cid = "0.10.1"
secrecy = "0.8.0"
serde = { version = "1.0.130", features = ["derive"], optional = true }
serde_json = "1.0"
getrandom = "0.2"

# serde default feature
[features]
default = ["serde"]

