# compose the *.wasm files together
build:
  cargo component build --workspace --release

compose: build
  wasm-tools compose -c compose-config.yml -o ./src/lib/full/aggregate.wasm ../../target/wasm32-wasi/release/delano_wit_ui.wasm

preview: build compose
  cd ../../sveltekit/ && npm run build && npm run preview -- --open
