name: Build Rust & Deploy Leptos Page

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "!*-rc[0-9]+"
  # push:
  #   branches: ["master"]
  # pull_request:
  #   branches: ["master"]
  workflow_dispatch:
    inputs:
      continue:
        type: boolean
        description: Do you wish to continue?
        default: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Exit if not on master branch
        if: endsWith(github.ref, 'master') == false
        run: exit -1

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-unknown, wasm32-wasi
          toolchain: nightly-x86_64-unknown-linux-gnu
          components: rust-src

      - name: Install binstall
        uses: taiki-e/install-action@cargo-binstall

      - name: Install cargo component
        run: echo yes | cargo binstall cargo-component

      - name: Cargo component build Workspace
        run: cargo component build --workspace

      - name: Run workspace tests
        run: cargo test --workspace --verbose

      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Build with trunk-rs
      - name: Install Trunk
        run: echo yes | cargo binstall trunk@0.17.5

      - name: Build and Deploy Leptos Directory
        run: cd crates/ && cd delano-leptos-site/ && trunk build --release --all-features
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./crates/delano-leptos-site/dist
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
